name: CMake Build & Test

on:
  push:
      branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: install dependencies
      run: sudo apt update && sudo apt install -y cmake g++ qtbase5-dev

    - name: create build folder
      run: mkdir build

    - name: going to build folder
      run: cd build

    - name: Configure CMake
      run: |
        cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/cmake/Qt5

    - name: Build project
      run: |
        cmake --build .

    - name: Run tests
      run: |
        ctest --output-on-failure
      continue-on-error: true

    - name: Send Telegram notification
      run: |
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
        -d chat_id=$TELEGRAM_CHAT_ID -d text="Build and Test completed successfully!"
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
